name: Get Lowlighter metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main", "1-apply-lowlighter-metrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

      - name: Generate metrics for ChatApplication
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.chatapplication.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: ChatApplication
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_delay: 30
          plugin_followup: yes

      - name: Generate metrics for blog
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.blog.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: kaestro.github.io
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_delay: 30
          plugin_followup: yes

      - name: Generate metrics for algorithms_v3
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.algorithms.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: algorithms_v3
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_delay: 30
          plugin_followup: yes