name: Get Lowlighter metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main", "1-apply-lowlighter-metrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - uses: lowlighter/metrics@main
        with:
          template: repository
          filename: metrics.chatapplication.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: ChatApplication
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1

      - uses: lowlighter/metrics@main
        with:
          template: repository
          filename: metrics.blog.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: kaestro.github.io
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1

      - uses: lowlighter/metrics@main
        with:
          template: repository
          filename: metrics.algorithms.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: algorithms_v3
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
